---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: java-web-app-docker
  name: java-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: java-web-app-docker
    spec:
      containers:
      - image: boddupallichanderrao/java-web-app-docker
        name: java-web-app-docker
        ports:
        - name: java-web-app-docker
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: java-web-app-docker
  name: java-web-app-docker
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: java-web-app-docker
